import hljs from 'highlight.js/lib/core';
import javascript from 'highlight.js/lib/languages/javascript';
hljs.registerLanguage('javascript', javascript);
import smalltalk from 'highlight.js/lib/languages/smalltalk';
hljs.registerLanguage('smalltalk', smalltalk);
import typescript from 'highlight.js/lib/languages/typescript';
hljs.registerLanguage('typescript', typescript);
import awk from 'highlight.js/lib/languages/awk';
hljs.registerLanguage('awk', awk);
import bash from 'highlight.js/lib/languages/bash';
hljs.registerLanguage('bash', bash);
import c from 'highlight.js/lib/languages/c';
hljs.registerLanguage('c', c);
import closure from 'highlight.js/lib/languages/closure';
hljs.registerLanguage('closure', closure);
import ceylon from 'highlight.js/lib/languages/ceylon';
hljs.registerLanguage('ceylon', ceylon);
import cpp from 'highlight.js/lib/languages/cpp';
hljs.registerLanguage('cpp', cpp);
import crystal from 'highlight.js/lib/languages/crystal';
hljs.registerLanguage('crystal', crystal);
import csharp from 'highlight.js/lib/languages/csharp';
hljs.registerLanguage('csharp', csharp);
import css from 'highlight.js/lib/languages/css';
hljs.registerLanguage('css', css);
import diff from 'highlight.js/lib/languages/diff';
hljs.registerLanguage('diff', diff);
import dockerfile from 'highlight.js/lib/languages/dockerfile';
hljs.registerLanguage('dockerfile', dockerfile);
import elixir from 'highlight.js/lib/languages/elixir';
hljs.registerLanguage('elixir', elixir);
import erlang from 'highlight.js/lib/languages/erlang';
hljs.registerLanguage('erlang', erlang);
import gradle from 'highlight.js/lib/languages/gradle';
hljs.registerLanguage('gradle', gradle);
import groovy from 'highlight.js/lib/languages/groovy';
hljs.registerLanguage('groovy', groovy);
import go from 'highlight.js/lib/languages/go';
hljs.registerLanguage('go', go);
import haskell from 'highlight.js/lib/languages/haskell';
hljs.registerLanguage('haskell', haskell);
import ini from 'highlight.js/lib/languages/ini';
hljs.registerLanguage('ini', ini);
import java from 'highlight.js/lib/languages/java';
hljs.registerLanguage('java', java);
import julia from 'highlight.js/lib/languages/julia';
hljs.registerLanguage('julia', julia);
import json from 'highlight.js/lib/languages/json';
hljs.registerLanguage('json', json);
import kotlin from 'highlight.js/lib/languages/kotlin';
hljs.registerLanguage('kotlin', kotlin);
import less from 'highlight.js/lib/languages/less';
hljs.registerLanguage('less', less);
import llvm from 'highlight.js/lib/languages/llvm';
hljs.registerLanguage('llvm', llvm);
import lua from 'highlight.js/lib/languages/lua';
hljs.registerLanguage('lua', lua);
import makefile from 'highlight.js/lib/languages/makefile';
hljs.registerLanguage('makefile', makefile);
import markdown from 'highlight.js/lib/languages/markdown';
hljs.registerLanguage('markdown', markdown);
import matlab from 'highlight.js/lib/languages/matlab';
hljs.registerLanguage('matlab', matlab);
import nginx from 'highlight.js/lib/languages/nginx';
hljs.registerLanguage('nginx', nginx);
import nim from 'highlight.js/lib/languages/nim';
hljs.registerLanguage('nim', nim);
import objectivec from 'highlight.js/lib/languages/objectivec';
hljs.registerLanguage('objectivec', objectivec);
import ocaml from 'highlight.js/lib/languages/ocaml';
hljs.registerLanguage('ocaml', ocaml);
import perl from 'highlight.js/lib/languages/perl';
hljs.registerLanguage('perl', perl);
import php from 'highlight.js/lib/languages/php';
hljs.registerLanguage('php', php);
import plaintext from 'highlight.js/lib/languages/plaintext';
hljs.registerLanguage('plaintext', plaintext);
import protobuf from 'highlight.js/lib/languages/protobuf';
hljs.registerLanguage('protobuf', protobuf);
import powershell from 'highlight.js/lib/languages/powershell';
hljs.registerLanguage('powershell', powershell);
import python from 'highlight.js/lib/languages/python';
hljs.registerLanguage('python', python);
import qml from 'highlight.js/lib/languages/qml';
hljs.registerLanguage('qml', qml);
import r from 'highlight.js/lib/languages/r';
hljs.registerLanguage('r', r);
import ruby from 'highlight.js/lib/languages/ruby';
hljs.registerLanguage('ruby', ruby);
import rust from 'highlight.js/lib/languages/rust';
hljs.registerLanguage('rust', rust);
import scala from 'highlight.js/lib/languages/scala';
hljs.registerLanguage('scala', scala);
import scss from 'highlight.js/lib/languages/scss';
hljs.registerLanguage('scss', scss);
import scheme from 'highlight.js/lib/languages/scheme';
hljs.registerLanguage('scheme', scheme);
import sql from 'highlight.js/lib/languages/sql';
hljs.registerLanguage('sql', sql);
import swift from 'highlight.js/lib/languages/swift';
hljs.registerLanguage('swift', swift);
import vbnet from 'highlight.js/lib/languages/vbnet';
hljs.registerLanguage('vbnet', vbnet);
import vhdl from 'highlight.js/lib/languages/vhdl';
hljs.registerLanguage('vhdl', vhdl);
import wasm from 'highlight.js/lib/languages/wasm';
hljs.registerLanguage('wasm', wasm);
import xml from 'highlight.js/lib/languages/xml';
hljs.registerLanguage('xml', xml);
import yaml from 'highlight.js/lib/languages/yaml';
hljs.registerLanguage('yaml', yaml);

const highlighter = hljs;
export default highlighter;